/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHARUK
 */
public class ManageCustomers extends javax.swing.JFrame {

    /**
     * Creates new form ManageCustomers
     */
    public ManageCustomers() {
        
        
        initComponents();
        displayCus();
    }
    
       public void displayCus(){

       try {
            BufferedReader br = new BufferedReader(new FileReader("Users.txt"));
            DefaultTableModel model= (DefaultTableModel)TABLE2.getModel();


            Object[] tableLines = br.lines().toArray();

           for(Object Car : tableLines)
            {
                String Line = Car.toString().trim();
                String[] dataRow = Line.split(";");
                String[] dataRow2 = {dataRow[0],dataRow[1],dataRow[3],dataRow[6],dataRow[5]};
                model.addRow(dataRow2);
            }
            br.close();
        } catch (IOException ex) {
            
            
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CusID = new javax.swing.JTextField();
        CusPasw = new javax.swing.JTextField();
        CusNum = new javax.swing.JTextField();
        editCus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TABLE2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        CusAdrs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ManageCar = new javax.swing.JButton();
        ManageCus = new javax.swing.JButton();
        Bookings = new javax.swing.JButton();
        Reports = new javax.swing.JButton();
        BookingHistory = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Address");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("Phone no");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("Customer ID");

        CusID.setBackground(new java.awt.Color(255, 255, 255));
        CusID.setForeground(new java.awt.Color(0, 153, 153));

        CusPasw.setBackground(new java.awt.Color(255, 255, 255));
        CusPasw.setForeground(new java.awt.Color(0, 153, 153));

        CusNum.setBackground(new java.awt.Color(255, 255, 255));
        CusNum.setForeground(new java.awt.Color(0, 153, 153));

        editCus.setBackground(new java.awt.Color(153, 102, 255));
        editCus.setForeground(new java.awt.Color(255, 255, 255));
        editCus.setText("Edit");
        editCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("Customer list");

        TABLE2.setBackground(new java.awt.Color(255, 255, 204));
        TABLE2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer id", "Name", "Phone no", "Password", "Address"
            }
        ));
        TABLE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TABLE2MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(TABLE2);

        jLabel17.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 102, 0));
        jLabel17.setText("Manage Customers");

        CusAdrs.setBackground(new java.awt.Color(255, 255, 255));
        CusAdrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusAdrsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CusID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CusNum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CusPasw, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CusAdrs, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editCus))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusPasw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusAdrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        jPanel6.setBackground(new java.awt.Color(153, 0, 255));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Rent Rabbit");

        ManageCar.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        ManageCar.setText("Manage Cars");
        ManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCarActionPerformed(evt);
            }
        });

        ManageCus.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        ManageCus.setText("Manage user");
        ManageCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCusActionPerformed(evt);
            }
        });

        Bookings.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        Bookings.setText("Bookings");
        Bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingsActionPerformed(evt);
            }
        });

        Reports.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        Reports.setText("Reports");
        Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsActionPerformed(evt);
            }
        });

        BookingHistory.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        BookingHistory.setText("Booking history");
        BookingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingHistoryActionPerformed(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ManageCar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(ManageCus)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(Bookings, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)))
                    .addComponent(BookingHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addGap(41, 41, 41))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ManageCar)
                .addGap(37, 37, 37)
                .addComponent(ManageCus)
                .addGap(37, 37, 37)
                .addComponent(Bookings)
                .addGap(37, 37, 37)
                .addComponent(Reports)
                .addGap(49, 49, 49)
                .addComponent(BookingHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingHistoryActionPerformed
        // TODO add your handling code here:
        
        BookingHistory rprt = new BookingHistory();
        rprt.setVisible(true);
        rprt.pack();
        rprt.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_BookingHistoryActionPerformed

    private void ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsActionPerformed
        // TODO add your handling code here:
        Report rprt = new Report();
        rprt.setVisible(true);
        rprt.pack();
        rprt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ReportsActionPerformed

    private void BookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingsActionPerformed
        // TODO add your handling code here:
        
        Bookings rprt = new Bookings();
        rprt.setVisible(true);
        rprt.pack();
        rprt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BookingsActionPerformed

    private void ManageCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCusActionPerformed
        // TODO add your handling code here:
        
        ManageCustomers regcr = new ManageCustomers();
        regcr.setVisible(true);
        regcr.pack();
        regcr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ManageCusActionPerformed

    private void ManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCarActionPerformed
        // TODO add your handling code here:
        ManageCar regcr = new ManageCar();
        regcr.setVisible(true);
        regcr.pack();
        regcr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ManageCarActionPerformed

    private void CusAdrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusAdrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusAdrsActionPerformed

    private void editCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCusActionPerformed
        // TODO add your handling code here:
        String cusTID= CusID.getText();
        String CusPH= CusNum.getText();
        String cusPass= CusPasw.getText();
        String CusAds= CusAdrs.getText();
        
        CusID.setText("");
        CusNum.setText("");
        CusPasw.setText("");
        CusAdrs.setText("");
        
        if(cusTID.equals("")||CusPH.equals("")||cusPass.equals("")||CusAds.equals("")){
            JOptionPane.showMessageDialog(null, "please dont leave anything empty");
        }
        else{
            
            ManageCusClass add = new ManageCusClass(cusTID,CusPH,cusPass,CusAds);
            boolean message = true;
            add.editCus(cusTID,CusPH,cusPass,CusAds);
            
            if (message == false){
                JOptionPane.showMessageDialog(null, "Modification unsuccessful");
            }
        }
        DefaultTableModel model = (DefaultTableModel)TABLE2.getModel();
        model.setRowCount(0);
        displayCus();
             
        
    }//GEN-LAST:event_editCusActionPerformed

    private void TABLE2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE2MouseReleased
        // TODO add your handling code here:
        
        int selectedRow = TABLE2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)TABLE2.getModel();
        CusID.setText(model.getValueAt(selectedRow, 0).toString());
        CusNum.setText(model.getValueAt(selectedRow, 2).toString());
        CusPasw.setText(model.getValueAt(selectedRow, 3).toString());
        CusAdrs.setText(model.getValueAt(selectedRow, 4).toString());
        
    }//GEN-LAST:event_TABLE2MouseReleased

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        
        UserLogin usrr = new UserLogin();
        usrr.setVisible(true);
        usrr.pack();
        usrr.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingHistory;
    private javax.swing.JButton Bookings;
    private javax.swing.JTextField CusAdrs;
    private javax.swing.JTextField CusID;
    private javax.swing.JTextField CusNum;
    private javax.swing.JTextField CusPasw;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ManageCar;
    private javax.swing.JButton ManageCus;
    private javax.swing.JButton Reports;
    private javax.swing.JTable TABLE2;
    private javax.swing.JButton editCus;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
